require: rubocop-rspec
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/spec_helper.rb'
    - 'lib/clock.rb:9'
    - 'lib/clock.rb:15'

Style/Encoding:
  Enabled: true

Metrics/LineLength:
  Max: 125

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/ClassVars:
  Enabled: false
