sudo: required
addons:
  code_climate:
    repo_token: 4bf4c1b9294323c889e569a756e84b178661d1e650a7190a89bac96285fae290
os: osx
before_install:
  - brew update
  - brew install sdl2
  - bundle install
language: ruby
rvm:
  - 2.2.3
